### ISSUE TITLE
Increasing consistancy in the emitted request logs

### ISSUE THREAD

**Issue by geo-bert** [mhatzl/web_ids#8]
The following changes need to be made to increase the consistancy between the signatures and the request logs:
-  Change the field name request_method to method
- Change the field name request_uri to uri
- Update the documentation in [doc/FetchingLogs.md](https://github.com/mhatzl/web_ids/blob/main/doc/FetchingLogs.md)

These improvements were mentioned [here](https://github.com/mhatzl/web_ids/pull/6#pullrequestreview-652689434) and [here](https://github.com/mhatzl/web_ids/pull/6#issuecomment-833331301)

EDIT: Fix typo

**Comment by geo-bert** [comment]
I misread [here](https://github.com/mhatzl/web_ids/pull/6#issuecomment-833328298). I'd rather have you, the pro, do this before I mess something up. I thought you meant in the signature files.

**Comment by mhatzl** [comment]
Ok sure, I can make the changes :) (not a pro actually :D)
